[build]
  publish = "site"
  command = "pip install -r requirements.txt && mkdocs build"

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
